axis_linear: 7  # Left thumb stick vertical
scale_linear: 1
scale_linear_turbo: 1

axis_angular: 3  # Left thumb stick horizontal
scale_angular: 3

enable_button: 4  # Left trigger button
enable_turbo_button: 5  # Right trigger button
